### ISSUE TITLE
Some of Opengeo packages are named improperly

### ISSUE THREAD

**Issue by benhosmer** [SS-archive/salt-states#13]
It seems I rushed through committing [this](https://github.com/saltstack/salt-states/commit/9318948de26beeef3017592bda9c54b00be42b29) one. Some of the package names don't exist.

I'll be updating these soon so that they all work.

**Comment by thatch45** [comment]
Thanks for adding this in as a reminder!

**Comment by benhosmer** [comment]
Sure thing. I think Clint is looking at it now.
