### ISSUE TITLE
`apt-key` behind a fire-wall

### ISSUE THREAD

**Issue by nemtsov** [SS-archive/salt-states#28]
I tried to install the `mongodb-10gen` state for a dev vm, and quickly realized that apt-key retrieves it's keys via port 11371, which was blocked by my corp. proxy. 

The work-around was to use `hkp://keyserver.ubuntu.com:80` instead of `keyserver.ubuntu.com` in the keyserver argument.

There are two references to apt-key in the "small" state:
- `small/lamp-drupal/init.sls`
- `small/mongodb-10gen/init.sls`

I'm not sure what this does in terms of security; but if you don't see any issue with this, I'll submit a pull-request.

**Comment by SEJeff** [comment]
@nemtsov Please do.
