### ISSUE TITLE
I can't find my lamp-stack

### ISSUE THREAD

**Issue by benhosmer** [SS-archive/salt-states#7]
I submitted a lamp-stack previously: https://github.com/saltstack/salt-states/commit/66a4c836718afc7ab14f29393243c42b74f8c4b5

But I can't find it now since the recent cleanup that herlo did. Am I missing it somewhere? I looked back through the commits and can't tell where it was even moved or deleted.

**Comment by thatch45** [comment]
https://github.com/saltstack/salt-states/blob/master/small/lamp-drupal/init.sls

I think it has not been moved

**Comment by benhosmer** [comment]
Sorry, I was blind!

**Comment by thatch45** [comment]
happens to the best of us :)
